### ISSUE TITLE
image_type="photo" gives error

### ISSUE THREAD

**Issue by passionetartufo** [Lukas0025/python-pixabay#8]
Hi, I was reading here https://github.com/Lukas0025/python-pixabay/blob/main/examples/advanceQuery.py
that I can basically use all the filters listed here https://pixabay.com/api/docs/
Is this right? I don't understand why if I use image_type="photo" gives error.
This is the error: TypeError: core.query() got an unexpected keyword argument 'image_type'
while the other filters works

**Comment by Lukas0025** [comment]
Hello, it look like imageType is not implemented parametr. When i have time
i added support for it. Current supported parameters is in auto generated
documentation on
https://python-pixabay.readthedocs.io/en/latest/classpixabay_1_1params_1_1params.html

Dne út 10. 1. 2023 17:01 uživatel giggioman00 ***@***.***>
napsal:

**Comment by passionetartufo** [comment]
Okay thanks. I also suppose that orientation is another parametr that is it not implemented yet? Could you please also add this parametr? Thanks

**Comment by Lukas0025** [comment]
Orientation should by implemented. I not tested it now but it is in
documentation
https://python-pixabay.readthedocs.io/en/latest/classpixabay_1_1core_1_1core.html#a0a2c46c79c85013f6f48e705e2aac027

When i have time i check if it working.

Dne út 10. 1. 2023 17:23 uživatel giggioman00 ***@***.***>
napsal:

**Comment by giggioman00** [comment]
Yes you are right thanks. 
Another question please. I'm trying to bulk download images from a list made of searches on Python, the only problem is that if a term gives 0 images, thw hole script stop working. I'm unsure how to check if the images results are 0 in order to skip to the next term, any tips on this please?

I blindly tried this with not much hope honestly, and indeed doesn't work

`if len(search_results)==0:
                    print(f"No results for term: {term}, skipping to the next term")
                    continue
                # get len of hits len(space)
                print("{} hits for term: {}".format(len(search_results), term))`
